platform :ios, '8.0'
use_frameworks!
target 'CocoaPod' do 
    pod 'Masonry'  #布局
    pod 'AFNetworking'#网络请求
    pod 'SDAutoLayout'#布局
    pod 'MBProgressHUD'#菊花
    pod 'Reachability'#实时监测网络状态
    pod 'MJRefresh'#加载-刷新
    pod 'MJExtension'#字典转模型框架
    pod 'FMDB'#数据库
    pod 'SDWebImage'#图片加载
    pod 'PLPlayerKit'#视频播放
    pod 'MMMaterialDesignSpinner'#指示器
end
